return {
  {
    "rose-pine/neovim",
    name = "rose-pine",
    lazy = false,
    priority = 1000,
    opts = {
      styles = {
        italic = false,
      },
      highlight_groups = {
        Comment = { italic = true },
        ["@comment"] = { italic = true },
        Keyword = { italic = true },
        ["@keyword"] = { italic = true },
        ["@keyword.function"] = { italic = true },
        ["@keyword.return"] = { italic = true },
        ["@keyword.operator"] = { italic = true },
        Conditional = { italic = true },
        ["@conditional"] = { italic = true },
        Repeat = { italic = true },
        ["@repeat"] = { italic = true },
      },
    },
  },
  { "neanias/everforest-nvim", name = "everforest" },
  { "sainnhe/edge", name = "edge" },
  { "sainnhe/sonokai", name = "sonokai" },
  { "sainnhe/gruvbox-material", name = "gruvbox-material" },
  { "AlexvZyl/nordic.nvim", name = "nordic" },
  { "everviolet/nvim", name = "evergarden" },
  { "projekt0n/github-nvim-theme", name = "github-theme" },
  { "nyoom-engineering/oxocarbon.nvim", name = "oxocarbon" },
  { "EdenEast/nightfox.nvim", name = "nightfox", opts = { styles = { comments = "italic" } } },
  { "rebelot/kanagawa.nvim", name = "kanagawa" },
  { "savq/melange-nvim", name = "melange" },
  { "kungfusheep/mfd.nvim", name = "mfd" },
  { "oskarnurm/koda.nvim", name = "koda", opts = { styles = { comments = { italic = true } } } },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "rose-pine",
    },
  },
}
